import { Switch, LineEdit, VerticalBox } from "std-widgets.slint";

export global ReceiveAdapter {
    in-out property <string> coin_address: "";
    in-out property <string> space_address: "";

    callback generate_address(bool);

    pure callback qr_code(string) -> image;
}

export component Receive inherits Rectangle {
    property <bool> is_space_address <=> switch.checked;

    function generate_address() {
        ReceiveAdapter.generate_address(is_space_address);
    }

    pure function current_address() -> string {
        is_space_address ? ReceiveAdapter.space_address : ReceiveAdapter.coin_address
    }

    init => {
        generate_address();
    }

    VerticalBox {
        alignment: start;
        vertical-stretch: 0;
        switch := Switch {
            text: "Space address";
            toggled => {
                generate_address();
            }
        }

        if (current_address() != ""): VerticalLayout {
            alignment: start;
            vertical-stretch: 0;
            LineEdit {
                text: current_address();
                read-only: true;
            }

            Image {
                preferred-width: 250px;
                preferred-height: 250px;
                source: ReceiveAdapter.qr_code(current_address());
            }
        }
    }
}
