import { Switch } from "std-widgets.slint";

export global ReceiveAdapter {
    in-out property <string> coin_address: "";
    in-out property <string> space_address: "";

    callback generate_address(bool);

    pure callback qr_code(string) -> image;
}

export component Receive inherits Rectangle {
    property <bool> is_space_address <=> switch.checked;

    function generate_address() {
        ReceiveAdapter.generate_address(is_space_address);
    }

    pure function current_address() -> string {
        is_space_address ? ReceiveAdapter.space_address : ReceiveAdapter.coin_address
    }

    init => {
        generate_address();
    }

    VerticalLayout {
        switch := Switch {
            text: "Space address";
            toggled => {
                generate_address();
            }
        }

        if (current_address() != ""): VerticalLayout {
            Text {
                text: current_address();
            }

            Image {
                source: ReceiveAdapter.qr_code(current_address());
            }
        }
    }
}
