import { LineEdit, Button, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Validators } from "../validators.slint";

export component SendPage inherits Rectangle {
    callback send(string, int);

    property <string> recipient;
    property <string> amount;

    property <bool> recipient_err;
    property <bool> amount_err;

    VerticalBox {
        Text {
            text: @tr("Recipient");
        }

        LineEdit {
            text <=> recipient;
            accepted => {
                submit.clicked();
            }
        }

        if recipient_err: Text {
            text: @tr("Recipient must be an address");
        }

        Text {
            text: @tr("Amount");
        }

        LineEdit {
            input-type: InputType.number;
            text <=> amount;
            accepted => {
                submit.clicked();
            }
        }

        if amount_err: Text {
            text: @tr("Amount must be a number");
        }

        submit := Button {
            text: @tr("Send");
            enabled: true;
            clicked => {
                if submit.enabled {
                    recipient_err = !Validators.is_coin_address(recipient);
                    amount_err = !amount.is-float();
                    if !recipient_err && !amount_err {
                        submit.enabled = false;
                        send(recipient, amount.to-float());
                    }
                }
            }
        }

        Rectangle { }
    }
}
