import { LineEdit } from "std-widgets.slint";

export global SpacesAdapter {
    in-out property <{
        name: string,
    }> space;

    pure callback validate_space(string) -> bool;
    callback load_space(string);
}

export component Spaces inherits Rectangle {
    VerticalLayout {
        HorizontalLayout {
            LineEdit {
                accepted => {
                    if (SpacesAdapter.validate_space(self.text)) {
                        SpacesAdapter.load_space(self.text);
                    }
                }
            }
        }

        if SpacesAdapter.space.name != "": Rectangle {
            Text {
                text: "@" + SpacesAdapter.space.name;
            }
        }

        Rectangle { }
    }
}
