import { LineEdit, Button, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Space } from "../types.slint";
import { Validators, ValidatorResult } from "../validators.slint";
import { QrCode } from "../components/qr_code.slint";

export component SpacePage inherits Rectangle {
    in property <Space> space;

    property <string> space_name;
    property <bool> space_name_err;
    callback load_space(string);

    VerticalBox {
        HorizontalBox {
            input := LineEdit {
                placeholder-text: @tr("Space name");
                edited(value) => {
                    if Validators.space_name(value) == ValidatorResult.Valid {
                        space_name = value;
                    } else if Validators.space_name(value) == ValidatorResult.Invalid {
                        space_name = value;
                    }
                    self.text = space_name;
                }
                accepted => {
                    submit.clicked();
                }
            }

            submit := Button {
                text: @tr("Search");
                clicked => {
                    space_name_err = false; //!Validators.is_space_name(input.text);
                    load_space(input.text);
                }
            }
        }

        if space_name_err: Text {
            text: @tr("Space name must be valid");
        }

        if space.name != "": Rectangle {
            Text {
                text: space.name;
            }
        }

        Rectangle { }
    }
}
