import { LineEdit, Button, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Space } from "../types.slint";
import { QrCode } from "../components/qr_code.slint";

export component SpacePage inherits Rectangle {
    in property <Space> space;
    callback load_space(string);

    VerticalBox {
        HorizontalBox {
            input := LineEdit {
                accepted => {
                    submit.clicked();
                }
            }

            submit := Button {
                text: @tr("Search");
                clicked => {
                    load_space(input.text);
                }
            }
        }

        if space.name != "": Rectangle {
            Text {
                text: space.name;
            }
        }

        Rectangle { }
    }
}
