import { LineEdit, Button, HorizontalBox, VerticalBox } from "std-widgets.slint";

export global SpacesAdapter {
    in-out property <{
        name: string,
    }> space;

    pure callback validate_space(string) -> bool;
    callback load_space(string);
}

export component Spaces inherits Rectangle {
    VerticalBox {
        HorizontalBox {
            input := LineEdit {
                accepted => {
                    submit.clicked();
                }
            }

            submit := Button {
                text: @tr("Search");
                clicked => {
                    if (SpacesAdapter.validate_space(input.text)) {
                        SpacesAdapter.load_space(input.text);
                    }
                }
            }
        }

        if SpacesAdapter.space.name != "": Rectangle {
            Text {
                text: "@" + SpacesAdapter.space.name;
            }
        }

        Rectangle { }
    }
}
