// Based on https://github.com/slint-ui/slint/blob/master/examples/gallery/ui/side_bar.slint

import { HorizontalBox, Palette } from "std-widgets.slint";

export component NavItem inherits Rectangle {
    background: Palette.control-background;
    in property <bool> selected;
    in property <string> text <=> label.text;

    callback clicked <=> touch.clicked;

    height: l.preferred-height;

    states [
        pressed when touch.pressed: {
            label.color: Palette.selection-foreground;
            state.opacity: 0.8;
        }
        hover when touch.has-hover: {
            label.color: Palette.selection-foreground;
            state.opacity: 0.6;
        }
        selected when root.selected: {
            label.color: Palette.selection-foreground;
            state.opacity: 1;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: Palette.selection-background;

        animate opacity { duration: 150ms; }
    }

    l := HorizontalBox {
        y: (parent.height - self.height) / 2;
        spacing: 0px;

        label := Text {
            font-size: 14px;
            vertical-alignment: center;
            color: Palette.control-foreground;

            animate color { duration: 150ms; }
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
        width: 100%;
        height: 100%;
    }
}
