// Based on https://github.com/slint-ui/slint/blob/master/examples/gallery/ui/side_bar.slint

import { HorizontalBox, Palette } from "std-widgets.slint";

component SideNavItem inherits Rectangle {
    in property <bool> selected;
    in property <string> text <=> label.text;

    callback clicked <=> touch.clicked;

    min-height: l.preferred-height;

    states [
        pressed when touch.pressed: {
            label.color: Palette.selection-foreground;
            state.opacity: 0.8;
        }
        hover when touch.has-hover: {
            label.color: Palette.selection-foreground;
            state.opacity: 0.6;
        }
        selected when root.selected: {
            label.color: Palette.selection-foreground;
            state.opacity: 1;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: Palette.selection-background;

        animate opacity { duration: 150ms; }
    }

    l := HorizontalBox {
        y: (parent.height - self.height) / 2;
        spacing: 0px;

        label := Text {
            vertical-alignment: center;
            color: Palette.control-foreground;

            animate color { duration: 150ms; }
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
        width: 100%;
        height: 100%;
    }
}

export component SideNav inherits Rectangle {
    in property <[string]> model: [];
    out property <int> current-item: 0;

    background: Palette.control-background;
    navigation := VerticalLayout {
        alignment: start;
        vertical-stretch: 0;
        for item[index] in root.model: SideNavItem {
            clicked => {
                root.current-item = index;
            }
            selected: index == root.current-item;
            text: item;
        }
    }
}
