[package]
name = "spaces-wallet"
version = "0.0.1"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "qr_code", "advanced"] }
spaced = { git = "https://github.com/Ximik/spaces.git", branch = "slabel" }
protocol = { git = "https://github.com/Ximik/spaces.git", branch = "slabel" }
wallet = { git = "https://github.com/Ximik/spaces.git", branch = "slabel" }
jsonrpsee = { version = "0.22.5", features = ["http-client"] }
clap = { version = "4.5.6", features = ["derive", "env"] }
hex = "0.4.3"
rustc-hash = "1.1"
verglas = { version = "0.1.2", features = ["index"] }

[build-dependencies]
verglas = { version = "0.1.2", features = ["forge"] }
