import { Palette } from "std-widgets.slint";

import { ReceiveAdapter, Receive } from "./pages/receive.slint";
export { ReceiveAdapter }

import { SpacesAdapter, Spaces } from "./pages/spaces.slint";
export { SpacesAdapter }

import { NavItem } from "./components/nav_item.slint";

export component AppWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Spaces Wallet");
    icon: @image-url("../assets/logo.png");

    in-out property <int> page: 0;

    HorizontalLayout {
        Rectangle {
            width: 200px;
            background: Palette.control-background;
            VerticalLayout {
                alignment: start;
                vertical-stretch: 0;
                Rectangle {
                    Image {
                        source: @image-url("../assets/logo.png");
                        width: 50px;
                        height: 50px;
                        horizontal-alignment: center;
                        image-fit: contain;
                    }
                }

                for item[index] in [
                    @tr("Home"),
                    @tr("Receive"),
                    @tr("Send"),
                    @tr("Spaces"),
                ]: NavItem {
                    selected: page == index;
                    text: item;
                    clicked => {
                        page = index
                    }
                }
            }
        }

        Rectangle {
            if(page == 0): Text {
                text: "HOME";
            }
            if(page == 1): Receive { }
            if(page == 2): Text {
                text: "SEND";
            }
            if(page == 3): Spaces { }
        }
    }
}
