import { Palette } from "std-widgets.slint";

import { ReceiveAdapter, ReceivePage } from "./pages/receive.slint";
export { ReceiveAdapter }

import { SideNav } from "./components/side_nav.slint";

export component AppWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Spaces Wallet");
    icon: @image-url("../assets/logo.png");

    HorizontalLayout {
        VerticalLayout {
            width: 200px;
            Rectangle {
                background: Palette.control-background;
                Image {
                    source: @image-url("../assets/logo.png");
                    width: 50px;
                    height: 50px;
                    horizontal-alignment: center;
                    image-fit: contain;
                }
            }

            Rectangle {
                side-bar := SideNav {
                    model: [
                        @tr("Home"),
                        @tr("Receive"),
                    ];
                }
            }
        }

        Rectangle {
            if(side-bar.current-item == 0): Text {
                text: "HOME";
            }
            if(side-bar.current-item == 1): ReceivePage { }
        }
    }
}
